import type { MediaSourceStatus, StockMediaAsset } from "@/lib/types";
import { buildDamFilenames } from "@/lib/dam-filenames";
import { imageUrlsForResource } from "@/lib/resourcespace-schema";

export const demoFallbackStatus: MediaSourceStatus = {
  adapter: "demo-fallback",
  label: "Local demo data",
  detail: "Hosted ResourceSpace export not connected in this environment. Records are read-only local demo data; source files remain restricted.",
  readOnly: true
};

const demoFallbackAssetRecords: StockMediaAsset[] = [
  {
    id: "367",
    title: "Bible Teaching Background",
    thumbnail: imageUrlsForResource("367").small,
    thumbnailAlt: "Open Bible teaching background",
    preview: imageUrlsForResource("367").detail,
    imageUrls: imageUrlsForResource("367"),
    mediaType: "photo",
    collection: "Teaching & Study",
    status: "Approved Public",
    usageScope: "Public",
    peopleRisk: "No people",
    sourcePlatform: "ResourceSpace",
    sourceSystem: "Read-only sample record",
    sourceAccount: "media.library@tjc.example",
    sourceAlbum: "Teaching & Study",
    sourceAlbumPath: "/private/review-sample/source-album",
    sourceAlbumMemberships: ["Teaching & Study"],
    sourcePath: "/private/review-sample/source.jpg",
    masterDrivePath: "/private/review-sample/master.jpg",
    originalFilename: "bible_teaching_background.jpg",
    resourceSpaceId: "367",
    imageDimensions: "2400 x 1600",
    rightsStatus: "Rights approved",
    consentStatus: "Consent confirmed",
    reviewer: "Rights Reviewer",
    reviewedDate: "2026-06-01",
    rightsNotes: "TJC-owned rights approved for public verification.",
    usageGuidance: "Approved for public ministry website, slides, and newsletter reuse.",
    downloadPolicy: "approved-copy-allowed",
    tags: ["Bible", "website", "landscape"],
    tjcTerms: ["Sabbath Service", "Religious Education"],
    usageTerms: ["website", "slides", "newsletter"],
    checksumSha256: "3673673673673673673673673673673673673673673673673673673673673673"
  },
  {
    id: "368",
    title: "Bench Bible",
    thumbnail: imageUrlsForResource("368").small,
    thumbnailAlt: "Bible on bench pending reuse review",
    preview: imageUrlsForResource("368").detail,
    imageUrls: imageUrlsForResource("368"),
    mediaType: "photo",
    collection: "Teaching & Study",
    status: "Approved Public",
    usageScope: "Public",
    peopleRisk: "Unknown",
    sourcePlatform: "ResourceSpace",
    sourceSystem: "Read-only sample record",
    sourceAccount: "review.queue@tjc.example",
    sourceAlbum: "Teaching & Study",
    sourceAlbumPath: "/private/review-sample/source-album",
    sourceAlbumMemberships: ["Teaching & Study"],
    sourcePath: "/private/review-sample/bench-bible-source.jpg",
    masterDrivePath: "/private/review-sample/bench-bible-master.jpg",
    originalFilename: "bench_bible.jpg",
    resourceSpaceId: "368",
    imageDimensions: "2400 x 1600",
    rightsStatus: "Unknown",
    consentStatus: "Unknown",
    reviewer: "Rights Reviewer",
    reviewedDate: "2026-06-01",
    rightsNotes: "Approved-status sample with rights and people review blockers.",
    usageGuidance: "Review rights and people/minors metadata before reuse.",
    downloadPolicy: "approved-copy-allowed",
    tags: ["Bible", "study"],
    tjcTerms: ["Sabbath Service", "Religious Education"],
    usageTerms: ["website", "slides"],
    checksumSha256: "3683683683683683683683683683683683683683683683683683683683683683"
  },
  {
    id: "644",
    title: "2012 Photo 644",
    thumbnail: imageUrlsForResource("644").small,
    thumbnailAlt: "2012 review sample",
    preview: imageUrlsForResource("644").detail,
    imageUrls: imageUrlsForResource("644"),
    mediaType: "photo",
    collection: "Fellowship",
    status: "Needs Review",
    usageScope: "Do Not Publish",
    peopleRisk: "Adults visible",
    sourcePlatform: "ResourceSpace",
    sourceSystem: "Read-only sample record",
    sourceAccount: "media.library@tjc.example",
    sourceAlbum: "Fellowship",
    sourceAlbumPath: "/private/review-sample/source-album",
    sourceAlbumMemberships: ["Fellowship"],
    sourcePath: "/private/review-sample/review-source.jpg",
    masterDrivePath: "/private/review-sample/review-master.jpg",
    originalFilename: "fellowship_review_644.jpg",
    resourceSpaceId: "644",
    imageDimensions: "2400 x 1600",
    rightsStatus: "Needs review",
    consentStatus: "Unknown",
    rightsNotes: "Needs reviewer approval before reuse.",
    usageGuidance: "Review required before ministry reuse.",
    downloadPolicy: "not-downloadable",
    tags: ["review", "fellowship"],
    tjcTerms: ["Fellowship"],
    usageTerms: ["internal review"],
    checksumSha256: "6446446446446446446446446446446446446446446446446446446446446446"
  },
  {
    id: "9101",
    title: "Bible Study Table",
    thumbnail: imageUrlsForResource("9101").small,
    thumbnailAlt: "Bible on a study table",
    preview: imageUrlsForResource("9101").detail,
    imageUrls: imageUrlsForResource("9101"),
    mediaType: "photo",
    collection: "Sabbath Service - Religious Education",
    status: "Approved Public",
    usageScope: "Public",
    peopleRisk: "No people",
    sourcePlatform: "Google Photos",
    sourceSystem: "LM Photos import",
    sourceAccount: "lm.photos@tjc.org",
    sourceAlbum: "Sabbath Service - Religious Education",
    sourceAlbumMemberships: ["Sabbath Service - Religious Education"],
    originalFilename: "LMPhotos_RE_Sabbath_BibleStudy_001.jpg",
    resourceSpaceId: "9101",
    imageDimensions: "2400 x 1600",
    rightsStatus: "TJC-owned",
    consentStatus: "not applicable",
    reviewer: "ResourceSpace admin",
    reviewedDate: "2026-06-04",
    rightsNotes: "Trusted LM Photos import sample. Public-approved stock-safe default for local beta discovery.",
    usageGuidance: "Approved for public ministry website, slides, and newsletter reuse.",
    downloadPolicy: "approved-copy-allowed",
    tags: ["Bible", "book", "classroom", "warm", "stock-safe"],
    tjcTerms: ["Sabbath Service", "Religious Education", "Bible study"],
    usageTerms: ["website", "slides", "newsletter", "stock-safe"],
    aiVisibleTagSuggestions: ["table", "open Bible", "study notes"],
    aiTjcTermSuggestions: ["Religious Education"],
    humanAiDecision: "edited"
  },
  {
    id: "9105",
    title: "Internal Teaching Handout",
    thumbnail: imageUrlsForResource("9105").small,
    thumbnailAlt: "Internal teaching handout approved copy",
    preview: imageUrlsForResource("9105").detail,
    imageUrls: imageUrlsForResource("9105"),
    mediaType: "photo",
    collection: "Internal Ministry",
    status: "Approved Internal",
    usageScope: "Internal",
    peopleRisk: "No people",
    sourcePlatform: "ResourceSpace",
    sourceSystem: "Read-only sample record",
    sourceAccount: "qa.sample@tjc.example",
    sourceAlbum: "Internal Ministry",
    sourceAlbumMemberships: ["Internal Ministry"],
    resourceSpaceId: "9105",
    imageDimensions: "1600 x 1200",
    rightsStatus: "Rights approved",
    consentStatus: "Consent confirmed",
    reviewer: "Rights Reviewer",
    reviewedDate: "2026-06-01",
    rightsNotes: "Internal-use approved copy sample for download gate verification.",
    usageGuidance: "Approved for internal ministry reference only.",
    downloadPolicy: "internal-approved-copy-allowed",
    tags: ["internal", "teaching", "stock-safe"],
    tjcTerms: ["Religious Education"],
    usageTerms: ["internal", "slides"]
  },
  {
    id: "9102",
    title: "Sabbath Flower Arrangement",
    thumbnail: "",
    thumbnailAlt: "Flower arrangement near church entry",
    mediaType: "photo",
    collection: "Sabbath Service Details",
    status: "Approved Public",
    usageScope: "Public",
    peopleRisk: "No people",
    sourcePlatform: "Google Photos",
    sourceSystem: "LM Photos import",
    sourceAccount: "lm.photos@tjc.org",
    sourceAlbum: "Sabbath Service Details",
    sourceAlbumMemberships: ["Sabbath Service Details"],
    originalFilename: "LMPhotos_Sabbath_Flowers_002.jpg",
    resourceSpaceId: "9102",
    imageDimensions: "2000 x 1600",
    rightsStatus: "TJC-owned",
    consentStatus: "not applicable",
    reviewer: "ResourceSpace admin",
    reviewedDate: "2026-06-04",
    rightsNotes: "Trusted LM Photos import sample. No people visible.",
    usageGuidance: "Approved for public worship detail, newsletter, and slide background reuse.",
    downloadPolicy: "approved-copy-allowed",
    tags: ["flower", "plant", "seasonal", "warm", "stock-safe"],
    tjcTerms: ["Sabbath Service", "welcome"],
    usageTerms: ["website", "slides", "newsletter", "stock-safe"],
    aiVisibleTagSuggestions: ["floral arrangement", "church detail"],
    humanAiDecision: "accepted"
  },
  {
    id: "9103",
    title: "Fellowship Testimony Pending",
    thumbnail: "",
    thumbnailAlt: "Fellowship testimony context pending review",
    mediaType: "photo",
    collection: "Incoming Fellowship",
    status: "Needs Review",
    usageScope: "Do Not Publish",
    peopleRisk: "Adults visible",
    sourcePlatform: "Google Drive",
    sourceSystem: "Contributor upload",
    sourceAccount: "media.intake@tjc.org",
    sourceAlbum: "Incoming Fellowship",
    sourceAlbumMemberships: ["Incoming Fellowship"],
    originalFilename: "Contributor_Testimony_Fellowship_003.jpg",
    resourceSpaceId: "9103",
    rightsStatus: "needs review",
    consentStatus: "unknown",
    sensitiveContext: "testimony context-safe until reviewer confirms usage.",
    rightsNotes: "Needs reviewer approval before public use.",
    usageGuidance: "Context-safe candidate only; reviewer approval required before reuse.",
    downloadPolicy: "not-downloadable",
    tags: ["people", "table", "context-safe"],
    tjcTerms: ["Fellowship", "Testimony"],
    usageTerms: ["context-safe", "internal review"],
    aiVisibleTagSuggestions: ["people", "gathering"],
    aiTjcTermSuggestions: ["Testimony"],
    aiPeopleOrMinorFlag: "people visible",
    humanAiDecision: "not reviewed"
  },
  {
    id: "9104",
    title: "Choir Hymn Archive Audio",
    thumbnail: "",
    thumbnailAlt: "Archive-only hymn recording",
    mediaType: "audio",
    collection: "Hymns of Praise Archive",
    status: "Searchable Archive",
    usageScope: "Archive Only",
    peopleRisk: "Unknown",
    sourcePlatform: "Google Drive",
    sourceSystem: "Archive import",
    sourceAccount: "archive@tjc.org",
    sourceAlbum: "Hymns of Praise Archive",
    sourceAlbumMemberships: ["Hymns of Praise Archive"],
    originalFilename: "HymnsOfPraise_Archive_004.mp3",
    resourceSpaceId: "9104",
    rightsStatus: "hymn rights review required",
    consentStatus: "unknown",
    sensitiveContext: "Music rights archive-only sample.",
    rightsNotes: "Archive-only reference. Do not use for public publishing.",
    usageGuidance: "Archive-only; request music rights review before any channel reuse.",
    downloadPolicy: "not-downloadable",
    tags: ["choir", "audio", "archive-only"],
    tjcTerms: ["Hymns of Praise", "Sabbath Service"],
    usageTerms: ["archive only", "archive-only"],
    aiVisibleTagSuggestions: ["audio recording"],
    aiTjcTermSuggestions: ["Hymns of Praise"],
    aiPeopleOrMinorFlag: "unknown",
    humanAiDecision: "not reviewed"
  },
  ...Array.from({ length: 8 }, (_, index) => {
    const id = `92${String(index).padStart(2, "0")}`;
    return {
      id,
      title: `Beta Library Sample ${index + 1}`,
      thumbnail: imageUrlsForResource(id).small,
      thumbnailAlt: `Beta library sample ${index + 1}`,
      preview: imageUrlsForResource(id).detail,
      imageUrls: imageUrlsForResource(id),
      mediaType: "photo" as const,
      collection: "Beta Library Samples",
      status: "Approved Public" as const,
      usageScope: "Public" as const,
      peopleRisk: "No people" as const,
      sourcePlatform: "ResourceSpace",
      sourceSystem: "Read-only sample record",
      sourceAccount: "media.library@tjc.example",
      sourceAlbum: "Beta Library Samples",
      sourceAlbumMemberships: ["Beta Library Samples"],
      resourceSpaceId: id,
      imageDimensions: "1800 x 1200",
      rightsStatus: "Rights approved",
      consentStatus: "Consent confirmed",
      reviewer: "Rights Reviewer",
      reviewedDate: "2026-06-01",
      rightsNotes: "TJC-owned pagination sample approved for public verification.",
      usageGuidance: "Approved for public verification and layout pagination testing.",
      downloadPolicy: "approved-copy-allowed" as const,
      tags: index % 2 ? ["flower", "newsletter", "stock-safe"] : ["Bible", "website", "stock-safe"],
      tjcTerms: index % 2 ? ["Sabbath Service", "Hymns of Praise"] : ["Sabbath Service", "Religious Education"],
      usageTerms: ["website", "slides", "newsletter"]
    };
  })
];

export const demoFallbackAssets: StockMediaAsset[] = demoFallbackAssetRecords.map((asset) => ({
  ...asset,
  damFilenames: buildDamFilenames(asset)
}));
