<?php

include_once "/var/www/html/include/boot.php";
include_once "/var/www/html/include/api_functions.php";
include_once "/var/www/html/include/login_functions.php";
include_once "/var/www/html/include/user_functions.php";

command_line_only();

$secrets_path = $argv[1] ?? "";
$secrets = [];
if ($secrets_path !== "" && is_file($secrets_path)) {
    $decoded = json_decode((string) file_get_contents($secrets_path), true);
    if (is_array($decoded)) {
        $secrets = $decoded;
    }
}

$roles = [
    "viewer" => [
        "group" => "TJC Viewer",
        "username" => "tjc_viewer",
        "fullname" => "TJC Local Viewer",
        "email" => "viewer@tjc-stock-media.local",
        "permissions" => "s,f*,j*,q,z1,z2,z3",
    ],
    "contributor" => [
        "group" => "TJC Contributor",
        "username" => "tjc_contributor",
        "fullname" => "TJC Local Contributor",
        "email" => "contributor@tjc-stock-media.local",
        "permissions" => "s,g,c,d,f*,j*,q,dtu,z1,z2,z3,e-1",
    ],
    "reviewer" => [
        "group" => "TJC Reviewer",
        "username" => "tjc_reviewer",
        "fullname" => "TJC Local Reviewer",
        "email" => "reviewer@tjc-stock-media.local",
        "permissions" => "s,g,c,t,h,r,u,i,e-2,e-1,e0,e1,e2,e3,v,q,f*,j*,R,Ra,Rb",
    ],
    "admin" => [
        "group" => "TJC DAM Admin",
        "username" => "tjc_admin",
        "fullname" => "TJC Local DAM Admin",
        "email" => "dam-admin@tjc-stock-media.local",
        "permissions" => "s,g,c,t,h,r,u,i,e-2,e-1,e0,e1,e3,v,o,m,q,f*,j*,k,R,Ra,Rb,x,hdta,lm,cm",
    ],
    "api" => [
        "group" => "TJC DAM Admin",
        "username" => "portal_api",
        "fullname" => "TJC Portal API",
        "email" => "portal-api@tjc-stock-media.local",
        "permissions" => "s,g,c,t,h,r,u,i,e-2,e-1,e0,e1,e3,v,o,m,q,f*,j*,k,R,Ra,Rb,x,hdta,lm,cm",
    ],
];

function seed_password_for_role(array $secrets, string $role): string
{
    $password = trim((string) ($secrets["credentials"][$role]["password"] ?? ""));
    if ($password !== "") {
        return $password;
    }
    return "Local1!" . substr(bin2hex(random_bytes(24)), 0, 24);
}

function ensure_local_usergroup(string $name, string $permissions): int
{
    static $refs = [];
    if (isset($refs[$name])) {
        return $refs[$name];
    }

    $matches = ps_query("SELECT ref FROM usergroup WHERE name = ? ORDER BY ref LIMIT 1", ["s", $name]);
    $existing = isset($matches[0]["ref"]) ? (int) $matches[0]["ref"] : 0;
    $options = [
        "name" => $name,
        "permissions" => $permissions,
        "request_mode" => 1,
        "welcome_message" => "Local TJC Stock Media role for ResourceSpace/portal testing.",
    ];
    if ($existing > 0) {
        save_usergroup($existing, $options);
        $refs[$name] = $existing;
        return $refs[$name];
    }
    $created = save_usergroup(0, $options);
    if (!is_int($created) || $created <= 0) {
        fwrite(STDERR, "FAIL: could not create user group {$name}\n");
        exit(1);
    }
    $refs[$name] = $created;
    return $refs[$name];
}

function ensure_local_user(array $role, int $group_ref, string $password): int
{
    $username = $role["username"];
    $password_hash = rs_password_hash("RS{$username}{$password}");
    $existing = (int) ps_value("SELECT ref value FROM user WHERE username = ?", ["s", $username], 0, "schema");
    if ($existing > 0) {
        ps_query(
            "UPDATE user SET password = ?, fullname = ?, email = ?, usergroup = ?, approved = 1, password_last_change = NOW(), email_invalid = 0 WHERE ref = ?",
            ["s", $password_hash, "s", $role["fullname"], "s", $role["email"], "i", $group_ref, "i", $existing]
        );
        return $existing;
    }
    ps_query(
        "INSERT INTO user (username, password, fullname, email, usergroup, comments, approved, password_last_change, email_invalid) VALUES (?, ?, ?, ?, ?, ?, 1, NOW(), 0)",
        [
            "s", $username,
            "s", $password_hash,
            "s", $role["fullname"],
            "s", $role["email"],
            "i", $group_ref,
            "s", "Local ResourceSpace test account generated by scripts/resourcespace-seed-local.php.",
        ]
    );
    return sql_insert_id();
}

$credential_rows = [];
$group_rows = [];
$api = null;

foreach ($roles as $key => $role) {
    $group_ref = ensure_local_usergroup($role["group"], $role["permissions"]);
    $password = seed_password_for_role($secrets, $key);
    $user_ref = ensure_local_user($role, $group_ref, $password);
    $row = [
        "role" => $key,
        "group" => $role["group"],
        "group_ref" => $group_ref,
        "username" => $role["username"],
        "password" => $password,
        "user_ref" => $user_ref,
    ];
    if ($key === "api") {
        $api = [
            "username" => $role["username"],
            "key" => get_api_key($user_ref),
            "userRef" => $user_ref,
        ];
    } else {
        $credential_rows[] = $row;
    }
    $group_rows[] = "{$role["group"]} ({$group_ref})";
}

$payload = [
    "ok" => true,
    "generatedAt" => gmdate("c"),
    "groups" => array_values(array_unique($group_rows)),
    "credentials" => $credential_rows,
    "api" => $api,
];

echo json_encode($payload, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . "\n";
